### ISSUE TITLE
Waiting for your review `nuxt/modules`

### ISSUE THREAD

**Issue by chakAs3** [antfu-sponsors/hi#3]
Hi @antfu would please have a quick review on this PR https://github.com/nuxt/modules/pull/777

**Comment by antfu** [comment]
For that I would need Pooya's review to proceed.

**Comment by chakAs3** [comment]
> For that I would need Pooya's review to proceed.

Ok no problem. thx man

**Comment by chakAs3** [comment]
@antfu  just curious why Pooya specifically ?

**Comment by antfu** [comment]
Because he was the one reviewing modules mainly, and also the maintainer of the previous version? I am not 100% understand the situation there (seems to be v3 rewrite replacing v2?), either way, I am not the right person to review. I would appreciate not pinging.
