### ISSUE TITLE
Please stop inviting

### ISSUE THREAD

**Issue by laverdet** [antfu-sponsors/hi#4]
Hi there I appreciate your work and want to provide financial support but otherwise remain hands off. I've turned down the invitation to the organization several times but it appears to be automated and comes back. Please respect my choice and only send 1 invitation. Thank you!

**Comment by antfu** [comment]
Sorry for that trouble, I was aware of that. I just pushed some changes to the script and ideally, it should persisted with the invited information. Let me know if it still doing the same. Thank you for your support.
